name: Build and test

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  csds_client:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Build
      run: make -C csds-client
    - name: Test
      run: make -C csds-client test
  envoy_curses:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: envoy-curses/package-lock.json
    - run: npm ci
      working-directory: envoy-curses
    - run: npm run lint
      working-directory: envoy-curses
    - run: npm test
      working-directory: envoy-curses
